/* adj_mc.h - generated by scripts/publish_headerless.py, do not edit.
 *
 * Interface of ../../services/multimedia/audio/process/adj_mc/src/adj_mc.c (closed BES implementation), reconstructed from the
 * DWARF debug information the vendor left in the prebuilt archive
 * (4 functions that no header in this tree declares).
 *
 * These are declarations only: types refer to definitions elsewhere in this tree,
 * the file is not guaranteed to compile standalone, and the implementation behind
 * it remains BES's proprietary code - declaration here grants no licence.
 */
#ifndef ANC_RECONSTRUCTED_ADJ_MC_H
#define ANC_RECONSTRUCTED_ADJ_MC_H

void adj_mc_init(uint32_t frame_len);  /* line 40 */
void adj_mc_deinit(void);  /* line 53 */
uint32_t adj_mc_filter_estimate(uint8_t * buf, uint32_t len);  /* line 60 */
int anc_adj_mc_run_mono(uint8_t * buf, int len, enum AUD_BITS_T sample_bit);  /* line 128 */

#endif /* ANC_RECONSTRUCTED_ADJ_MC_H */
