/* cmsis_fftwrap.h - generated by scripts/publish_headerless.py, do not edit.
 *
 * Interface of ../../services/multimedia/speech/src/process/common/cmsis_fftwrap.c (closed BES implementation), reconstructed from the
 * DWARF debug information the vendor left in the prebuilt archive
 * (4 functions that no header in this tree declares).
 *
 * These are declarations only: types refer to definitions elsewhere in this tree,
 * the file is not guaranteed to compile standalone, and the implementation behind
 * it remains BES's proprietary code - declaration here grants no licence.
 * Scope and prior art: docs/prior-art.md in this repository.
 */
#ifndef ANC_RECONSTRUCTED_CMSIS_FFTWRAP_H
#define ANC_RECONSTRUCTED_CMSIS_FFTWRAP_H

void * cmsis_f32_fft_init(int size, int mode);  /* line 35 */
void cmsis_f32_fft_destroy(void * table);  /* line 59 */
void cmsis_f32_fft(void * table, float * in, float * out);  /* line 73 */
void cmsis_f32_ifft(void * table, float * in, float * out);  /* line 110 */

#endif /* ANC_RECONSTRUCTED_CMSIS_FFTWRAP_H */
