/* drc.h - generated by scripts/publish_headerless.py, do not edit.
 *
 * Interface of ../../services/multimedia/audio/process/drc/src/drc.cpp (closed BES implementation), reconstructed from the
 * DWARF debug information the vendor left in the prebuilt archive
 * (5 functions that no header in this tree declares).
 *
 * These are declarations only: types refer to definitions elsewhere in this tree,
 * the file is not guaranteed to compile standalone, and the implementation behind
 * it remains BES's proprietary code - declaration here grants no licence.
 * Scope and prior art: docs/prior-art.md in this repository.
 */
#ifndef ANC_RECONSTRUCTED_DRC_H
#define ANC_RECONSTRUCTED_DRC_H

void crossover_filter_2band<short int>(struct drc_filter_st * drc_filter_low, const int ch, const int ch_interleaved, const short int * ChBufPtrBand0, const short int * ChBufPtrBand1, float * Filter0, float * Filter1, const int DrcFrameLen);  /* line 7 */
void crossover_filter_2band<int>(struct drc_filter_st * drc_filter_low, const int ch, const int ch_interleaved, const int * ChBufPtrBand0, const int * ChBufPtrBand1, float * Filter0, float * Filter1, const int DrcFrameLen);  /* line 7 */
void update_drc_filter_freq(DrcState * st, int band_num, const int * filter_index);  /* line 86 */
void crossover_filter_3band<short int>(struct drc_filter_st * drc_filter_low, struct drc_filter_st * drc_filter_high, const int ch, const int ch_interleaved, const short int * ChBufPtrBand0, const short int * ChBufPtrBand1, float * Filter0, float * Filter1, float * Filter2, const int DrcFrameLen);  /* line 95 */
void crossover_filter_3band<int>(struct drc_filter_st * drc_filter_low, struct drc_filter_st * drc_filter_high, const int ch, const int ch_interleaved, const int * ChBufPtrBand0, const int * ChBufPtrBand1, float * Filter0, float * Filter1, float * Filter2, const int DrcFrameLen);  /* line 95 */

#endif /* ANC_RECONSTRUCTED_DRC_H */
