/* dual_mic_denoise.h - generated by scripts/publish_headerless.py, do not edit.
 *
 * Interface of ../../services/multimedia/speech/src/process/dual_mic_denoise/dual_mic_denoise.c (closed BES implementation), reconstructed from the
 * DWARF debug information the vendor left in the prebuilt archive
 * (8 functions that no header in this tree declares).
 *
 * These are declarations only: types refer to definitions elsewhere in this tree,
 * the file is not guaranteed to compile standalone, and the implementation behind
 * it remains BES's proprietary code - declaration here grants no licence.
 * Scope and prior art: docs/prior-art.md in this repository.
 */
#ifndef ANC_RECONSTRUCTED_DUAL_MIC_DENOISE_H
#define ANC_RECONSTRUCTED_DUAL_MIC_DENOISE_H

void pld_algorithm(short int * input, int framelen, short int * out);  /* line 212 */
void dc_filter(short int * in, int len);  /* line 520 */
void Mean_Var_filter(short int * in, int len);  /* line 542 */
void init_mic_h2f(short int * in, short int len);  /* line 565 */
void preprocess_pld_algorithm(short int * in, short int * out, short int len);  /* line 632 */
void time_domain_process(short int * in, short int len);  /* line 653 */
void corre_cal(short int * in, short int len, short int delay);  /* line 718 */
void param_init(const DUAL_MIC_DENOISE_CFG_T * cfg);  /* line 835 */

#endif /* ANC_RECONSTRUCTED_DUAL_MIC_DENOISE_H */
