/* far_field_speech_enhancement.h - generated by scripts/publish_headerless.py, do not edit.
 *
 * Interface of ../../services/multimedia/speech/src/process/far_field_speech_enhancement/far_field_speech_enhancement.c (closed BES implementation), reconstructed from the
 * DWARF debug information the vendor left in the prebuilt archive
 * (25 functions that no header in this tree declares).
 *
 * These are declarations only: types refer to definitions elsewhere in this tree,
 * the file is not guaranteed to compile standalone, and the implementation behind
 * it remains BES's proprietary code - declaration here grants no licence.
 * Scope and prior art: docs/prior-art.md in this repository.
 */
#ifndef ANC_RECONSTRUCTED_FAR_FIELD_SPEECH_ENHANCEMENT_H
#define ANC_RECONSTRUCTED_FAR_FIELD_SPEECH_ENHANCEMENT_H

float abs_cmpx_flt(float tmp1, float tmp2);  /* line 452 */
int abs_cmpx_int(FftData_t XX);  /* line 486 */
void matrix_mult(float * A, float * B, float * tmp);  /* line 506 */
void speech_mat_cmplx_mult_f32(float * A, float * B, float * tmp);  /* line 514 */
void matrix_mult_asm(float * A, float * B, float * tmp);  /* line 522 */
void matrix_add(float * B, float * A);  /* line 551 */
void cpx_matrix_mult(FltData_t * A, FltData_t * B, FltData_t * tmp);  /* line 559 */
void cpx_matrix_mult_asm(FltData_t * A, FltData_t * B, FltData_t * tmp);  /* line 571 */
void cpx_matrix_inv(FltData_t * Que, FltData_t * invQue);  /* line 691 */
void cpx_matrix_svd(FltData_t * Yen, float * cnd);  /* line 812 */
void VAD_Init(void);  /* line 877 */
void VAD_deinit(void);  /* line 888 */
short int HighPassFilterL(short int x0);  /* line 1042 */
short int HighPassFilterR(short int x0);  /* line 1056 */
void get_single_mic_data_HighPass(short int * in);  /* line 1070 */
void get_single_mic_data(short int * in);  /* line 1079 */
void get_two_mic_data(short int * in, short int * out);  /* line 1088 */
void get_two_mic_data_test(short int * in, short int * out);  /* line 1096 */
void DCfilter(short int * in1, short int * in2, int len);  /* line 1103 */
void estimate_delay_gcc_phat(short int * Sig1, short int * Sig2, int nfft, float * shift, float * val);  /* line 1162 */
void SubBandDecompositionPreprocess(short int * Sig, short int * In64SubBand, short int * AnaTapDelayLine, int lenSig, short int * AnaFilterCoef, int M, int R);  /* line 1298 */
void SubBandDecompositionProcess(short int * In64SubBand, short int * Out64SubBand, int lenSig);  /* line 1340 */
void SubBandDecompositionPostprocess(short int * Out64SubBand, int lenSig, int M);  /* line 1357 */
void SubBandSynthProcess(short int * Sig, short int * Sig64SubBandOut, int lenSig);  /* line 1392 */
void SubBandSynthPostProcess(short int * Sig, short int * SynOut, int * synTapDelayLine, int lenSig, short int * SynFilterCoef, int M, int R);  /* line 1434 */

#endif /* ANC_RECONSTRUCTED_FAR_FIELD_SPEECH_ENHANCEMENT_H */
