/* fft128dot.h - generated by scripts/publish_headerless.py, do not edit.
 *
 * Interface of ../../services/multimedia/algorithm/fft/src/fft128dot.cpp (closed BES implementation), reconstructed from the
 * DWARF debug information the vendor left in the prebuilt archive
 * (2 functions that no header in this tree declares).
 *
 * These are declarations only: types refer to definitions elsewhere in this tree,
 * the file is not guaranteed to compile standalone, and the implementation behind
 * it remains BES's proprietary code - declaration here grants no licence.
 */
#ifndef ANC_RECONSTRUCTED_FFT128DOT_H
#define ANC_RECONSTRUCTED_FFT128DOT_H

unsigned int log2_st(long unsigned int N);  /* line 48 */
void radix4bfly(FftData_t xa, FftData_t xb, FftData_t xc, FftData_t xd, FftTwiddle_t wa, FftTwiddle_t wb, FftTwiddle_t wc, FftTwiddle_t wd, ? ya, ? yb, ? yc, ? yd, int shift, int scale, bool round, int dataWidth, FftMode_t ifft, int pass);  /* line 240 */

#endif /* ANC_RECONSTRUCTED_FFT128DOT_H */
