/* fftfilt.h - generated by scripts/publish_headerless.py, do not edit.
 *
 * Interface of ../../services/multimedia/speech/src/process/speech_fir_calibration/fftfilt.cpp (closed BES implementation), reconstructed from the
 * DWARF debug information the vendor left in the prebuilt archive
 * (5 functions that no header in this tree declares).
 *
 * These are declarations only: types refer to definitions elsewhere in this tree,
 * the file is not guaranteed to compile standalone, and the implementation behind
 * it remains BES's proprietary code - declaration here grants no licence.
 * Scope and prior art: docs/prior-art.md in this repository.
 */
#ifndef ANC_RECONSTRUCTED_FFTFILT_H
#define ANC_RECONSTRUCTED_FFTFILT_H

short int ssat<short int>(float x);  /* line 90 */
float ssat<float>(float x);  /* line 90 */
int16_t ssat(float x);  /* line 95 */
void fftfilt_process_native<short int>(FftFiltState * st, short int * buf, int frame_size, int stride);  /* line 153 */
void fftfilt_process_native<float>(FftFiltState * st, float * buf, int frame_size, int stride);  /* line 153 */

#endif /* ANC_RECONSTRUCTED_FFTFILT_H */
