/* fftfilt2.h - generated by scripts/publish_headerless.py, do not edit.
 *
 * Interface of ../../services/multimedia/audio/process/adj_mc/src/fftfilt2.cpp (closed BES implementation), reconstructed from the
 * DWARF debug information the vendor left in the prebuilt archive
 * (5 functions that no header in this tree declares).
 *
 * These are declarations only: types refer to definitions elsewhere in this tree,
 * the file is not guaranteed to compile standalone, and the implementation behind
 * it remains BES's proprietary code - declaration here grants no licence.
 */
#ifndef ANC_RECONSTRUCTED_FFTFILT2_H
#define ANC_RECONSTRUCTED_FFTFILT2_H

short int ssat2<short int>(float x);  /* line 75 */
float ssat2<float>(float x);  /* line 75 */
int16_t ssat2(float x);  /* line 80 */
void fftfilt2_process_native<short int>(FftFilt2State * st, float * filter, short int * buf, int frame_size, int stride);  /* line 149 */
void fftfilt2_process_native<float>(FftFilt2State * st, float * filter, float * buf, int frame_size, int stride);  /* line 149 */

#endif /* ANC_RECONSTRUCTED_FFTFILT2_H */
