/* fftwrap.h - generated by scripts/publish_headerless.py, do not edit.
 *
 * Interface of ../../services/multimedia/speech/src/process/ns_and_ec/fftwrap.c (closed BES implementation), reconstructed from the
 * DWARF debug information the vendor left in the prebuilt archive
 * (23 functions that no header in this tree declares).
 *
 * These are declarations only: types refer to definitions elsewhere in this tree,
 * the file is not guaranteed to compile standalone, and the implementation behind
 * it remains BES's proprietary code - declaration here grants no licence.
 * Scope and prior art: docs/prior-art.md in this repository.
 */
#ifndef ANC_RECONSTRUCTED_FFTWRAP_H
#define ANC_RECONSTRUCTED_FFTWRAP_H

void * spx_kiss_fft_init(int size);  /* line 326 */
void spx_kiss_fft_destroy(void * table);  /* line 343 */
void spx_kiss_fft(void * table, spx_word16_t * in, spx_word16_t * out);  /* line 358 */
void spx_kiss_ifft(void * table, spx_word16_t * in, spx_word16_t * out);  /* line 394 */
void * spx_cmsis_fft_init(int size);  /* line 498 */
void spx_cmsis_fft_destroy(void * table);  /* line 516 */
void spx_cmsis_fft(void * table, spx_int16_t * in, spx_int16_t * out);  /* line 526 */
void spx_cmsis_ifft(void * table, spx_int16_t * in, spx_int16_t * out);  /* line 549 */
void * spx_cmsis_f32_fft_init(int size);  /* line 586 */
void spx_cmsis_f32_fft_destroy(void * table);  /* line 601 */
void spx_cmsis_f32_fft(void * table, float * in, float * out);  /* line 611 */
void spx_cmsis_f32_ifft(void * table, float * in, float * out);  /* line 634 */
void add_to_table(struct fft_config * table);  /* line 667 */
void * fft_create(int size, enum FFToptimization opt);  /* line 749 */
void fft_destroy(void * table);  /* line 794 */
void * spx_fft_init_opt(int size, enum FFToptimization opt);  /* line 886 */
void * spx_fft_init(int size);  /* line 903 */
void spx_fft_destroy(void * table);  /* line 912 */
void spx_fft(void * table, void * in, void * out);  /* line 923 */
void spx_ifft(void * table, void * in, void * out);  /* line 958 */
int spx_get_fft_num(void);  /* line 993 */
void spx_fft_float(void * table, float * in, float * out);  /* line 1080 */
void spx_ifft_float(void * table, float * in, float * out);  /* line 1084 */

#endif /* ANC_RECONSTRUCTED_FFTWRAP_H */
