/* fir2iir.h - generated by scripts/publish_headerless.py, do not edit.
 *
 * Interface of ../../services/multimedia/audio/process/fir2iir/src/fir2iir.c (closed BES implementation), reconstructed from the
 * DWARF debug information the vendor left in the prebuilt archive
 * (22 functions that no header in this tree declares).
 *
 * These are declarations only: types refer to definitions elsewhere in this tree,
 * the file is not guaranteed to compile standalone, and the implementation behind
 * it remains BES's proprietary code - declaration here grants no licence.
 */
#ifndef ANC_RECONSTRUCTED_FIR2IIR_H
#define ANC_RECONSTRUCTED_FIR2IIR_H

Complext complexsub(Complext a, Complext b);  /* line 36 */
Complext complexadd(Complext a, Complext b);  /* line 44 */
Complext complexmult(Complext a, Complext b);  /* line 52 */
Complext realcmpxmult(double a, Complext b);  /* line 60 */
Complext complexdiv(Complext tmp, Complext m);  /* line 68 */
double complexmodule(Complext a);  /* line 78 */
void sortqueue(double * x, short int * index, short int * flag, short int len);  /* line 85 */
int jacobi_svd(double * Mat, double * U, double * V, double * S, short int rows, short int cols);  /* line 116 */
Complext sqrtn(Complext x, short int n);  /* line 215 */
int polrt(double * xcof, double * cof, int m, double * real, double * imag, int * flag);  /* line 230 */
void poly(Complext * x, double * d, int order);  /* line 395 */
void polystab(double * a, double * b, int order, Complext * v, int * cnjflag);  /* line 422 */
void FilterGen(Complext * zerosin, Complext * polesin, double factor, int * cnjflagp, int * cnjflagz, int order, double[] * iircoefbb, double[] * iircoefaa);  /* line 443 */
void OMGen(Complext * OM, int FFTLen, int order);  /* line 559 */
void DmatGen(Complext * OM, Complext * Ht, double * weight, Complext * Dva, int denorder, int numorder, int FFTLen);  /* line 569 */
void ComplexHMatrixMult(Complext * Dva, double * R, int rows, int cols);  /* line 589 */
void ComplexMatrixMult(Complext * Dva, Complext * Ht, double * weight, double * Vd, int rows, int cols);  /* line 610 */
void ComplexMatrixMultNoWght(Complext * Dva, Complext * Err, double * Vd, int rows, int cols);  /* line 629 */
double GCmatGen(Complext * OM, double * NumCoef, double * DenCoef, Complext * GCmat, Complext * aOM, Complext * Err, Complext * Ht, double * weight, int denorder, int numorder, int HalfLen);  /* line 649 */
void D3matGen(Complext * OM, double * weight, Complext * GCmat, Complext * aOM, Complext * D3, int denorder, int numorder, int HalfLen);  /* line 671 */
void MatrixInversion(double * R, double * Vd, double * Acoef, int denorder, int numorder);  /* line 694 */
void FirtoIIRConvert(Complext * Ht, double * weight, int numorder, int denorder, int HalfLen, int maxiter, Complext * roots, double * Dcoef, double * Numb, int * cnjflag);  /* line 764 */

#endif /* ANC_RECONSTRUCTED_FIR2IIR_H */
