/* hw_iir_process_best2300p.h - generated by scripts/publish_headerless.py, do not edit.
 *
 * Interface of ../../services/multimedia/audio/process/filters/src/best2300p/hw_iir_process_best2300p.c (closed BES implementation), reconstructed from the
 * DWARF debug information the vendor left in the prebuilt archive
 * (1 functions that no header in this tree declares).
 *
 * These are declarations only: types refer to definitions elsewhere in this tree,
 * the file is not guaranteed to compile standalone, and the implementation behind
 * it remains BES's proprietary code - declaration here grants no licence.
 */
#ifndef ANC_RECONSTRUCTED_HW_IIR_PROCESS_BEST2300P_H
#define ANC_RECONSTRUCTED_HW_IIR_PROCESS_BEST2300P_H

int hw_iir_set_cfg_ch(const HW_IIR_FILTERS_T * iir_filters, enum AUD_CHANNEL_NUM_T ch);  /* line 941 */

#endif /* ANC_RECONSTRUCTED_HW_IIR_PROCESS_BEST2300P_H */
