/* iir_process.h - generated by scripts/publish_headerless.py, do not edit.
 *
 * Interface of ../../services/multimedia/audio/process/filters/src/iir_process.cpp (closed BES implementation), reconstructed from the
 * DWARF debug information the vendor left in the prebuilt archive
 * (10 functions that no header in this tree declares).
 *
 * These are declarations only: types refer to definitions elsewhere in this tree,
 * the file is not guaranteed to compile standalone, and the implementation behind
 * it remains BES's proprietary code - declaration here grants no licence.
 * Scope and prior art: docs/prior-art.md in this repository.
 */
#ifndef ANC_RECONSTRUCTED_IIR_PROCESS_H
#define ANC_RECONSTRUCTED_IIR_PROCESS_H

int getMaxEqBand(void);  /* line 80 */
int getSampleArray(uint8_t * buf, uint16_t * num);  /* line 85 */
int iir_run_per_samp_opt<int>(uint8_t * buf, int len);  /* line 273 */
int iir_run_per_samp_opt<short int>(uint8_t * buf, int len);  /* line 273 */
int iir_run_per_samp_opt_left<int>(uint8_t * buf, int len);  /* line 459 */
int iir_run_per_samp_opt_left<short int>(uint8_t * buf, int len);  /* line 459 */
int iir_run_impl(uint8_t * buf, uint32_t len);  /* line 667 */
int iir_update_running_cfg(const IIR_RUN_CFG_T * cfg);  /* line 869 */
int iir_backup_running_history(IIR_RUN_CFG_T * cfg);  /* line 889 */
int iir_set_coef(uint8_t index, const float * a, const float * b);  /* line 921 */

#endif /* ANC_RECONSTRUCTED_IIR_PROCESS_H */
