/* kiss_fftr.h - generated by scripts/publish_headerless.py, do not edit.
 *
 * Interface of ../../services/multimedia/speech/src/process/ns_and_ec/kiss_fftr.c (closed BES implementation), reconstructed from the
 * DWARF debug information the vendor left in the prebuilt archive
 * (5 functions that no header in this tree declares).
 *
 * These are declarations only: types refer to definitions elsewhere in this tree,
 * the file is not guaranteed to compile standalone, and the implementation behind
 * it remains BES's proprietary code - declaration here grants no licence.
 * Scope and prior art: docs/prior-art.md in this repository.
 */
#ifndef ANC_RECONSTRUCTED_KISS_FFTR_H
#define ANC_RECONSTRUCTED_KISS_FFTR_H

kiss_fftr_cfg kiss_fftr_alloc(int nfft, int inverse_fft, void * mem, size_t * lenmem);  /* line 41 */
void kiss_fftr(kiss_fftr_cfg st, const spx_int16_t * timedata, kiss_fft_cpx * freqdata);  /* line 99 */
void kiss_fftri(kiss_fftr_cfg st, const kiss_fft_cpx * freqdata, spx_int16_t * timedata);  /* line 154 */
void kiss_fftr2(kiss_fftr_cfg st, const spx_int16_t * timedata, spx_int16_t * freqdata);  /* line 191 */
void kiss_fftri2(kiss_fftr_cfg st, const spx_int16_t * freqdata, spx_int16_t * timedata);  /* line 279 */

#endif /* ANC_RECONSTRUCTED_KISS_FFTR_H */
