/* leftright_denoise.h - generated by scripts/publish_headerless.py, do not edit.
 *
 * Interface of ../../services/multimedia/speech/src/process/leftright_denoise/leftright_denoise.c (closed BES implementation), reconstructed from the
 * DWARF debug information the vendor left in the prebuilt archive
 * (7 functions that no header in this tree declares).
 *
 * These are declarations only: types refer to definitions elsewhere in this tree,
 * the file is not guaranteed to compile standalone, and the implementation behind
 * it remains BES's proprietary code - declaration here grants no licence.
 */
#ifndef ANC_RECONSTRUCTED_LEFTRIGHT_DENOISE_H
#define ANC_RECONSTRUCTED_LEFTRIGHT_DENOISE_H

void firfilterF_leftright(LeftRightDenoiseState * st, short int * buf, short int * FilterCoefF);  /* line 120 */
void firfilterR_leftright(LeftRightDenoiseState * st, short int * buf, short int delay);  /* line 150 */
LeftRightDenoiseState * leftright_denoise_fixed_create(int32_t sample_rate, int32_t frame_size, const LeftRightDenoiseConfig * cfg);  /* line 168 */
int32_t leftright_denoise_fixed_destroy(LeftRightDenoiseState * st);  /* line 233 */
int32_t leftright_denoise_fixed_set_config(LeftRightDenoiseState * st, const LeftRightDenoiseConfig * cfg);  /* line 267 */
int32_t leftright_denoise_fixed_process(LeftRightDenoiseState * st, short int * pcm_buf, int32_t pcm_len, short int * out_buf);  /* line 797 */
int32_t leftright_denoise_fixed_get_delay(LeftRightDenoiseState * st);  /* line 820 */

#endif /* ANC_RECONSTRUCTED_LEFTRIGHT_DENOISE_H */
