/* leftright_denoise_float.h - generated by scripts/publish_headerless.py, do not edit.
 *
 * Interface of ../../services/multimedia/speech/src/process/leftright_denoise/leftright_denoise_float.c (closed BES implementation), reconstructed from the
 * DWARF debug information the vendor left in the prebuilt archive
 * (5 functions that no header in this tree declares).
 *
 * These are declarations only: types refer to definitions elsewhere in this tree,
 * the file is not guaranteed to compile standalone, and the implementation behind
 * it remains BES's proprietary code - declaration here grants no licence.
 */
#ifndef ANC_RECONSTRUCTED_LEFTRIGHT_DENOISE_FLOAT_H
#define ANC_RECONSTRUCTED_LEFTRIGHT_DENOISE_FLOAT_H

LeftRightDenoiseState * leftright_denoise_float_create(int32_t sample_rate, int32_t frame_size, const LeftRightDenoiseConfig * cfg);  /* line 162 */
int32_t leftright_denoise_float_destroy(LeftRightDenoiseState * st);  /* line 223 */
int32_t leftright_denoise_float_set_config(LeftRightDenoiseState * st, const LeftRightDenoiseConfig * cfg);  /* line 258 */
int32_t leftright_denoise_float_process(LeftRightDenoiseState * st, short int * pcm_buf, int32_t pcm_len, short int * out_buf);  /* line 633 */
int32_t leftright_denoise_float_get_delay(LeftRightDenoiseState * st);  /* line 656 */

#endif /* ANC_RECONSTRUCTED_LEFTRIGHT_DENOISE_FLOAT_H */
