/* real_fft.h - generated by scripts/publish_headerless.py, do not edit.
 *
 * Interface of ../../services/multimedia/speech/src/process/speech_process_lib/common_audio/signal_processing/real_fft.c (closed BES implementation), reconstructed from the
 * DWARF debug information the vendor left in the prebuilt archive
 * (4 functions that no header in this tree declares).
 *
 * These are declarations only: types refer to definitions elsewhere in this tree,
 * the file is not guaranteed to compile standalone, and the implementation behind
 * it remains BES's proprietary code - declaration here grants no licence.
 */
#ifndef ANC_RECONSTRUCTED_REAL_FFT_H
#define ANC_RECONSTRUCTED_REAL_FFT_H

struct RealFFT * WebRtcSpl_CreateRealFFT(int order);  /* line 21 */
void WebRtcSpl_FreeRealFFT(struct RealFFT * self);  /* line 38 */
int WebRtcSpl_RealForwardFFT(struct RealFFT * self, const int16_t * real_data_in, int16_t * complex_data_out);  /* line 48 */
int WebRtcSpl_RealInverseFFT(struct RealFFT * self, const int16_t * complex_data_in, int16_t * real_data_out);  /* line 75 */

#endif /* ANC_RECONSTRUCTED_REAL_FFT_H */
