/* speech_win.h - generated by scripts/publish_headerless.py, do not edit.
 *
 * Interface of ../../services/multimedia/speech/src/process/common/speech_win.c (closed BES implementation), reconstructed from the
 * DWARF debug information the vendor left in the prebuilt archive
 * (5 functions that no header in this tree declares).
 *
 * These are declarations only: types refer to definitions elsewhere in this tree,
 * the file is not guaranteed to compile standalone, and the implementation behind
 * it remains BES's proprietary code - declaration here grants no licence.
 * Scope and prior art: docs/prior-art.md in this repository.
 */
#ifndef ANC_RECONSTRUCTED_SPEECH_WIN_H
#define ANC_RECONSTRUCTED_SPEECH_WIN_H

const short int * get_conj_win_half_128(int frame_size, int * shift);  /* line 82 */
const short int * get_conj_win_half_256(int frame_size, int * shift);  /* line 96 */
const short int * get_conj_win_half_512(int frame_size, int * shift);  /* line 112 */
const short int * get_conj_win_half(int win_size, int frame_size, int * shift);  /* line 128 */
const float * get_conj_win_f32(int win_size, int frame_size, _Bool cp);  /* line 158 */

#endif /* ANC_RECONSTRUCTED_SPEECH_WIN_H */
