/* speech_ff_2mic_ns2.h - generated by scripts/publish_headerless.py, do not edit.
 *
 * Interface of ../../services/multimedia/speech/src/process/speech_ff_2mic_ns2/speech_ff_2mic_ns2.c (closed BES implementation), reconstructed from the
 * DWARF debug information the vendor left in the prebuilt archive
 * (2 functions that no header in this tree declares).
 *
 * These are declarations only: types refer to definitions elsewhere in this tree,
 * the file is not guaranteed to compile standalone, and the implementation behind
 * it remains BES's proprietary code - declaration here grants no licence.
 * Scope and prior art: docs/prior-art.md in this repository.
 */
#ifndef ANC_RECONSTRUCTED_SPEECH_FF_2MIC_NS2_H
#define ANC_RECONSTRUCTED_SPEECH_FF_2MIC_NS2_H

int speech_ff_2mic_ns2_set_config(SpeechFF2MicNs2State * st);  /* line 59 */
short int prob_process(SpeechFF2MicNs2State * st, int16_t * pcm_buf, int32_t pcm_len);  /* line 242 */

#endif /* ANC_RECONSTRUCTED_SPEECH_FF_2MIC_NS2_H */
