/* speech_mics_calibration.h - generated by scripts/publish_headerless.py, do not edit.
 *
 * Interface of ../../services/multimedia/speech/src/process/speech_mics_calibration/speech_mics_calibration.c (closed BES implementation), reconstructed from the
 * DWARF debug information the vendor left in the prebuilt archive
 * (7 functions that no header in this tree declares).
 *
 * These are declarations only: types refer to definitions elsewhere in this tree,
 * the file is not guaranteed to compile standalone, and the implementation behind
 * it remains BES's proprietary code - declaration here grants no licence.
 * Scope and prior art: docs/prior-art.md in this repository.
 */
#ifndef ANC_RECONSTRUCTED_SPEECH_MICS_CALIBRATION_H
#define ANC_RECONSTRUCTED_SPEECH_MICS_CALIBRATION_H

int time2freq(SPEECH_MICS_CALIBRATION_T * st, int16_t * pcm_mic1, int16_t * pcm_mic2, int32_t pcm_len);  /* line 257 */
int freq2time(SPEECH_MICS_CALIBRATION_T * st, int16_t * pcm_mic1, int16_t * pcm_mic2, int32_t pcm_len);  /* line 317 */
int analysis_psd(SPEECH_MICS_CALIBRATION_T * st);  /* line 375 */
int sum_psd(SPEECH_MICS_CALIBRATION_T * st);  /* line 398 */
int32_t generate_calibration_coef(SPEECH_MICS_CALIBRATION_T * st);  /* line 422 */
int apply_calibration(SPEECH_MICS_CALIBRATION_T * st);  /* line 432 */
int analysis_freq_mse(SPEECH_MICS_CALIBRATION_T * st);  /* line 449 */

#endif /* ANC_RECONSTRUCTED_SPEECH_MICS_CALIBRATION_H */
