/* speech_ff_3mic_ns1.h - generated by scripts/publish_headerless.py, do not edit.
 *
 * Interface of ../../services/multimedia/speech/src/process/speech_ff_3mic_ns1/speech_ff_3mic_ns1.c (closed BES implementation), reconstructed from the
 * DWARF debug information the vendor left in the prebuilt archive
 * (2 functions that no header in this tree declares).
 *
 * These are declarations only: types refer to definitions elsewhere in this tree,
 * the file is not guaranteed to compile standalone, and the implementation behind
 * it remains BES's proprietary code - declaration here grants no licence.
 * Scope and prior art: docs/prior-art.md in this repository.
 */
#ifndef ANC_RECONSTRUCTED_SPEECH_FF_3MIC_NS1_H
#define ANC_RECONSTRUCTED_SPEECH_FF_3MIC_NS1_H

int speech_ff_3mic_ns1_set_config(SpeechFF3MicNs1State * st);  /* line 57 */
void speech_ff_3mic_ns1_process(SpeechFF3MicNs1State * st, short int * inF, short int * inR, short int * inS, short int * Ref);  /* line 258 */

#endif /* ANC_RECONSTRUCTED_SPEECH_FF_3MIC_NS1_H */
