/* speech_hwfir_calibration.h - generated by scripts/publish_headerless.py, do not edit.
 *
 * Interface of ../../services/multimedia/speech/src/process/speech_fir_calibration/speech_hwfir_calibration.c (closed BES implementation), reconstructed from the
 * DWARF debug information the vendor left in the prebuilt archive
 * (3 functions that no header in this tree declares).
 *
 * These are declarations only: types refer to definitions elsewhere in this tree,
 * the file is not guaranteed to compile standalone, and the implementation behind
 * it remains BES's proprietary code - declaration here grants no licence.
 * Scope and prior art: docs/prior-art.md in this repository.
 */
#ifndef ANC_RECONSTRUCTED_SPEECH_HWFIR_CALIBRATION_H
#define ANC_RECONSTRUCTED_SPEECH_HWFIR_CALIBRATION_H

SpeechFirCalibState * speech_hwfir_calib_init(int32_t sample_rate, int32_t frame_size, const SpeechFirCalibConfig * config);  /* line 59 */
void speech_hwfir_calib_destroy(SpeechFirCalibState * st);  /* line 139 */
void speech_hwfir_calib_process(SpeechFirCalibState * st, int16_t * buf, int32_t frame_size);  /* line 158 */

#endif /* ANC_RECONSTRUCTED_SPEECH_HWFIR_CALIBRATION_H */
