/* speech_arm_biquad_cascade_df1_init_f32.h - generated by scripts/publish_headerless.py, do not edit.
 *
 * Interface of ../../services/multimedia/speech/src/process/speech_iir/speech_arm_biquad_cascade_df1_init_f32.c (closed BES implementation), reconstructed from the
 * DWARF debug information the vendor left in the prebuilt archive
 * (1 functions that no header in this tree declares).
 *
 * These are declarations only: types refer to definitions elsewhere in this tree,
 * the file is not guaranteed to compile standalone, and the implementation behind
 * it remains BES's proprietary code - declaration here grants no licence.
 */
#ifndef ANC_RECONSTRUCTED_SPEECH_ARM_BIQUAD_CASCADE_DF1_INIT_F32_H
#define ANC_RECONSTRUCTED_SPEECH_ARM_BIQUAD_CASCADE_DF1_INIT_F32_H

void speech_arm_biquad_cascade_df1_init_f32(speech_arm_biquad_casd_df1_inst_f32 * S, uint8_t numStages, float32_t * pCoeffs, float32_t * pState);  /* line 88 */

#endif /* ANC_RECONSTRUCTED_SPEECH_ARM_BIQUAD_CASCADE_DF1_INIT_F32_H */
