/* speech_2mic_ns2_denoise.h - generated by scripts/publish_headerless.py, do not edit.
 *
 * Interface of ../../services/multimedia/speech/src/process/speech_2mic_ns2_denoise/speech_2mic_ns2_denoise.c (closed BES implementation), reconstructed from the
 * DWARF debug information the vendor left in the prebuilt archive
 * (8 functions that no header in this tree declares).
 *
 * These are declarations only: types refer to definitions elsewhere in this tree,
 * the file is not guaranteed to compile standalone, and the implementation behind
 * it remains BES's proprietary code - declaration here grants no licence.
 */
#ifndef ANC_RECONSTRUCTED_SPEECH_2MIC_NS2_DENOISE_H
#define ANC_RECONSTRUCTED_SPEECH_2MIC_NS2_DENOISE_H

void firfilterF_coherent(Speech2MicNs2State * st, short int * buf, short int * FilterCoefF);  /* line 159 */
void firfilterR_coherent(Speech2MicNs2State * st, short int * buf, short int delay);  /* line 190 */
Speech2MicNs2State * speech_2mic_ns2_fixed_create(int32_t sample_rate, int32_t frame_size, const Speech2MicNs2Config * cfg);  /* line 241 */
int32_t speech_2mic_ns2_fixed_destroy(Speech2MicNs2State * st);  /* line 315 */
int32_t speech_2mic_ns2_fixed_set_config(Speech2MicNs2State * st, const Speech2MicNs2Config * cfg);  /* line 358 */
int32_t speech_2mic_ns2_fixed_process(Speech2MicNs2State * st, short int * pcm_buf, int32_t pcm_len, short int * out_buf);  /* line 890 */
int32_t speech_2mic_ns2_fixed_get_delay(Speech2MicNs2State * st);  /* line 917 */
float speech_2mic_ns2_fixed_get_required_mips(Speech2MicNs2State * st);  /* line 923 */

#endif /* ANC_RECONSTRUCTED_SPEECH_2MIC_NS2_DENOISE_H */
