/* speech_3mic_ns.h - generated by scripts/publish_headerless.py, do not edit.
 *
 * Interface of ../../services/multimedia/speech/src/process/speech_3mic_ns/speech_3mic_ns.c (closed BES implementation), reconstructed from the
 * DWARF debug information the vendor left in the prebuilt archive
 * (2 functions that no header in this tree declares).
 *
 * These are declarations only: types refer to definitions elsewhere in this tree,
 * the file is not guaranteed to compile standalone, and the implementation behind
 * it remains BES's proprietary code - declaration here grants no licence.
 */
#ifndef ANC_RECONSTRUCTED_SPEECH_3MIC_NS_H
#define ANC_RECONSTRUCTED_SPEECH_3MIC_NS_H

void firfilterF(Speech3MicNsState * st, short int * buf, short int * FilterCoefF);  /* line 163 */
void firfilterR(Speech3MicNsState * st, short int * buf, short int delay);  /* line 194 */

#endif /* ANC_RECONSTRUCTED_SPEECH_3MIC_NS_H */
