/* speech_dc_filter.h - generated by scripts/publish_headerless.py, do not edit.
 *
 * Interface of ../../services/multimedia/speech/src/process/speech_dc_filter/speech_dc_filter.cpp (closed BES implementation), reconstructed from the
 * DWARF debug information the vendor left in the prebuilt archive
 * (2 functions that no header in this tree declares).
 *
 * These are declarations only: types refer to definitions elsewhere in this tree,
 * the file is not guaranteed to compile standalone, and the implementation behind
 * it remains BES's proprietary code - declaration here grants no licence.
 */
#ifndef ANC_RECONSTRUCTED_SPEECH_DC_FILTER_H
#define ANC_RECONSTRUCTED_SPEECH_DC_FILTER_H

int32_t speech_dc_filter_process<int>(SpeechDcFilterState * st, int * pcm_buf, int32_t pcm_len);  /* line 139 */
int32_t speech_dc_filter_process<short int>(SpeechDcFilterState * st, short int * pcm_buf, int32_t pcm_len);  /* line 139 */

#endif /* ANC_RECONSTRUCTED_SPEECH_DC_FILTER_H */
