/* triple_mic_denoise3.h - generated by scripts/publish_headerless.py, do not edit.
 *
 * Interface of ../../services/multimedia/speech/src/process/triple_mic_denoise3/triple_mic_denoise3.c (closed BES implementation), reconstructed from the
 * DWARF debug information the vendor left in the prebuilt archive
 * (1 functions that no header in this tree declares).
 *
 * These are declarations only: types refer to definitions elsewhere in this tree,
 * the file is not guaranteed to compile standalone, and the implementation behind
 * it remains BES's proprietary code - declaration here grants no licence.
 */
#ifndef ANC_RECONSTRUCTED_TRIPLE_MIC_DENOISE3_H
#define ANC_RECONSTRUCTED_TRIPLE_MIC_DENOISE3_H

int32_t triple_mic_denoise3_get_delay(TripleMicDenoise3State * st);  /* line 111 */

#endif /* ANC_RECONSTRUCTED_TRIPLE_MIC_DENOISE3_H */
