/* wind_detection_2mic.h - generated by scripts/publish_headerless.py, do not edit.
 *
 * Interface of ../../services/multimedia/speech/src/process/wind_detection_2mic/wind_detection_2mic.c (closed BES implementation), reconstructed from the
 * DWARF debug information the vendor left in the prebuilt archive
 * (1 functions that no header in this tree declares).
 *
 * These are declarations only: types refer to definitions elsewhere in this tree,
 * the file is not guaranteed to compile standalone, and the implementation behind
 * it remains BES's proprietary code - declaration here grants no licence.
 */
#ifndef ANC_RECONSTRUCTED_WIND_DETECTION_2MIC_H
#define ANC_RECONSTRUCTED_WIND_DETECTION_2MIC_H

float WindDetection2Mic_process(WindDetection2MicState * st, float * inF, float * inR, uint32_t sample_bits, uint32_t frame_len, float * wind_power);  /* line 292 */

#endif /* ANC_RECONSTRUCTED_WIND_DETECTION_2MIC_H */
