/* window_generator.h - generated by scripts/publish_headerless.py, do not edit.
 *
 * Interface of ../../services/multimedia/speech/src/process/spectrum/window_generator.c (closed BES implementation), reconstructed from the
 * DWARF debug information the vendor left in the prebuilt archive
 * (1 functions that no header in this tree declares).
 *
 * These are declarations only: types refer to definitions elsewhere in this tree,
 * the file is not guaranteed to compile standalone, and the implementation behind
 * it remains BES's proprietary code - declaration here grants no licence.
 */
#ifndef ANC_RECONSTRUCTED_WINDOW_GENERATOR_H
#define ANC_RECONSTRUCTED_WINDOW_GENERATOR_H

void hanning_window(float * w, int len);  /* line 19 */

#endif /* ANC_RECONSTRUCTED_WINDOW_GENERATOR_H */
