#!/usr/bin/env python3
"""Inspect the closed BES blobs shipped inside OpenPineBuds and write docs/closed-blobs.md.

Works on a clone of upstream (default /tmp/opb, override with OPB_CLONE or argv[1]).
Only metadata is extracted: object/function names, DWARF source paths, compile flags,
section sizes and exported-symbol usage. No decompilation.
"""
import re, subprocess, sys, os, pathlib, collections

OPB = pathlib.Path(sys.argv[1] if len(sys.argv) > 1 else os.environ.get("OPB_CLONE", "/tmp/opb"))
ROOT = pathlib.Path(__file__).resolve().parent.parent
if not (OPB / ".git").exists():
    raise SystemExit(f"no OpenPineBuds clone at {OPB}")

def sh(cmd, **kw):
    return subprocess.run(cmd, capture_output=True, text=True, errors="replace", **kw).stdout

libs = sorted(p for p in OPB.rglob("*.a") if ".git" not in p.parts)
inventory, missing_all, dwarf_sources = [], collections.Counter(), {}
for lib in libs:
    rel = str(lib.relative_to(OPB))
    members = sh(["ar", "t", str(lib)]).split()
    text_bytes = sh(["strings", "-n", "6", str(lib)])
    srcs = set(re.findall(r"(?:\.\./)+([A-Za-z0-9_./+-]+\.(?:c|cc|cpp|S|s))", text_bytes))
    dwarf_sources[rel] = srcs
    missing = sorted(p for p in srcs if not (OPB / p).exists())
    for m in missing:
        missing_all[m] += 1
    size = sh(["size", "-t", str(lib)]).strip().split("\n")[-1].split()
    gcc = sorted(set(re.findall(r"GNU C\d+ [0-9.]+ [0-9]{8}", text_bytes)))
    # DWARF is announced by the producer string (only emitted with -g)
    has_dbg = "yes" if re.search(r"GNU C\d+ \d", text_bytes) else "no"
    inventory.append({"lib": rel, "objs": len(members), "text": int(size[0]) if size else 0,
                      "data": int(size[1]) if size else 0, "bss": int(size[2]) if size else 0,
                      "dwarf": has_dbg, "gcc": gcc[0] if gcc else "",
                      "srcs": len(srcs), "missing": len(missing)})

# how far the open part reaches into each blob
src_files = [p for p in OPB.rglob("*") if p.suffix in {".c", ".h", ".cpp", ".S", ".s"}
             and ".git" not in p.parts]
idents = set(re.findall(r"[A-Za-z_][A-Za-z0-9_]{3,}",
                        "\n".join(p.read_text(errors="replace") for p in src_files)))
coupling = []
for lib in libs:
    names = [w for w in sh(["nm", "-g", "--defined-only", str(lib)]).split()
             if re.match(r"^[A-Za-z_][A-Za-z0-9_]+$", w)]
    used = [n for n in names if n in idents]
    coupling.append((str(lib.relative_to(OPB)), len(names), len(used)))

# compile flags / build dirs leaked by DWARF
flags, builddirs = set(), set()
for lib in libs:
    out = sh(["strings", "-n", "6", str(lib)])
    flags |= set(re.findall(r"GNU C99 [^\x00]{0,400}", out))
    builddirs |= set(re.findall(r"/home/[A-Za-z0-9_./-]+/out/[A-Za-z0-9_]+", out))

# flat per-file list for the relicensing effort: paths and categories only, no code
import json as _json
_protos = collections.Counter()
_hp = ROOT / "data" / "headerless-api.json"
if _hp.exists():
    _d = _json.loads(_hp.read_text())
    _recs = _d["functions"] if isinstance(_d, dict) and "functions" in _d else _d
    for _r in _recs:
        _s = (_r.get("source") or "").replace("../", "")
        if _s:
            _protos[_s] += 1
_gen = set()
for _h in sorted((ROOT / "include" / "anc_reconstructed").glob("*.h")):
    _m = re.search(r"Interface of (\S+) \(closed BES", _h.read_text(errors="replace"))
    if _m:
        _gen.add(_m.group(1).replace("../", "").lstrip("/"))
_rows = [["vendor_source", "archives_naming_it", "category", "prototypes_recovered", "generated_header"]]
for _path, _n in sorted(missing_all.items()):
    _tp = _path.startswith("thirdparty/") or any(k in _path for k in ("fdkaac", "lhdc", "ldac"))
    _rows.append([_path, str(_n), "third-party" if _tp else "BES",
                  str(_protos.get(_path, "")), "yes" if _path in _gen else ""])
(ROOT / "data" / "withheld-sources.tsv").write_text("\n".join("\t".join(r) for r in _rows) + "\n")
print(f"wrote data/withheld-sources.tsv ({len(_rows) - 1} files)")

stamp = __import__("datetime").date.today().isoformat()
L = [f"# What is inside the closed blobs ({stamp})", "",
     f"Metadata-level survey of the {len(libs)} prebuilt `*.a` archives linked by the OpenPineBuds "
     "`open_source` build: object names, DWARF records, compile flags, sizes and API usage. "
     "Generated by `scripts/blobmap.py`. No decompilation is performed.", "",
     "## Inventory", "", "| library | objects | .text bytes | DWARF | toolchain | DWARF sources | absent from tree |",
     "|---|---:|---:|---|---|---:|---:|"]
for r in sorted(inventory, key=lambda r: -r["text"]):
    L.append(f"| `{r['lib']}` | {r['objs']} | {r['text']:,} | {r['dwarf']} | {r['gcc']} | {r['srcs']} | {r['missing']} |")
L += ["", f"Totals: {sum(r['objs'] for r in inventory)} objects, "
          f"{sum(r['text'] for r in inventory):,} bytes of `.text` across all library variants.",
      "", "## What the DWARF gives away", ""]
for f in sorted(flags)[:3]:
    L.append(f"- compile flags: `{f[:300]}`")
for b in sorted(builddirs)[:5]:
    L.append(f"- build directory: `{b}`")
L += ["", "DWARF (`-g`) is present in the multimedia, BLE, BT-API, BT-profiles, LDAC, crypto and "
      "anc_spp_tool archives: compilation-unit source paths, function names with declaration line "
      "numbers, line tables and type names. The IBRT core/UI/OTA, LHDC and intersyshci archives "
      "carry no debug info (symbols only).", "",
      "## Source files referenced by the blobs but absent from the open tree", "",
      f"{len(missing_all)} distinct files. Top directories:", ""]
for d, c in collections.Counter("/".join(m.split("/")[:4]) for m in missing_all).most_common(15):
    L.append(f"- {c:4}  `{d}`")
L += ["", "## How far the open code reaches into the blobs", "",
      "| library | exported symbols | referenced by open sources |", "|---|---:|---:|"]
for lib, n, u in sorted(coupling, key=lambda c: -c[1]):
    L.append(f"| `{lib}` | {n} | {u} ({100 * u // max(n, 1)}%) |")
L += ["", "## Reading", "",
      "- The DWARF is enough to document interfaces, function names, line-level behaviour and data "
      "layout, and to cross-reference which upstream files were withheld.",
      "- The prebuilt part is not a thin shim: the multimedia archive alone exports thousands of "
      "symbols and holds ~1.1 MB of code per variant.",
      "- Third-party licensed code sits inside the blobs (Fraunhofer FDK-AAC under "
      "`services/multimedia/audio/codec/fdkaac_codec`, Savitech LHDC, Sony LDAC), so those parts "
      "cannot be relicensed as open source regardless of what BES decides.",
      "- Reimplementing code learned from these blobs is still reverse engineering of BES "
      "proprietary code; it does not create an open-source licence for the result.", ""]
(ROOT / "docs" / "closed-blobs.md").write_text("\n".join(L))
print(f"wrote docs/closed-blobs.md ({len(libs)} libs, {len(missing_all)} withheld sources)")
