#!/usr/bin/env python3
"""Publish the part of the closed API that no shipped header declares.

Recovers prototypes from the blobs' DWARF (scripts/dwarf_protos.py), keeps those
whose name appears in no header of the open tree, and writes:
  docs/headerless-api.md        human-readable inventory, grouped by source file
  data/headerless-api.json      machine-readable records
  include/anc_reconstructed/    one generated header per vendor source file
"""
import json, re, subprocess, sys, pathlib, tempfile, collections
sys.path.insert(0, str(pathlib.Path(__file__).resolve().parent))
import dwarf_protos as dp

OPB = pathlib.Path(sys.argv[1] if len(sys.argv) > 1 else "/tmp/opb")
LIB = OPB / "services/multimedia/lib/best2300p_libmultimedia_cp_anc.a"
FILT = re.compile(sys.argv[2] if len(sys.argv) > 2 else
                  r"(anc|adj_mc|iir|fft|eq|drc|wind|denoise|speech|vqe|dsp)")
ROOT = pathlib.Path(__file__).resolve().parent.parent

headers = list(OPB.rglob("*.h"))
htext = "\n".join(h.read_text(errors="replace") for h in headers)

members = subprocess.run(["ar", "t", str(LIB)], capture_output=True, text=True).stdout.split()
tmp = pathlib.Path(tempfile.mkdtemp())
subprocess.run(["ar", "x", str(LIB)], cwd=tmp, check=True)
recs, seen = [], {}
for obj in members:
    if not FILT.search(obj) or not (tmp / obj).exists():
        continue
    source, protos, _ = dp.prototypes(tmp / obj)
    for p in protos:
        r = {"name": p["name"], "return": p["return"], "args": p["args"], "static": p["static"],
             "line": p["line"], "source": source, "object": obj,
             "declared_in_tree_header": bool(re.search(r"\b" + re.escape(p["name"]) + r"\s*\(", htext))}
        if r["name"] in seen:                      # same function seen in another object/CU
            seen[r["name"]]["objects"].append(obj)
            continue
        r["objects"] = [obj]
        seen[r["name"]] = r
        recs.append(r)

headless = [r for r in recs if not r["declared_in_tree_header"]]
ext = [r for r in headless if not r["static"]]
statics = [r for r in headless if r["static"]]
promotable = [r for r in ext if "?" not in r["return"] and not any("?" in a["type"] for a in r["args"])]

(ROOT / "data").mkdir(exist_ok=True)
(ROOT / "data" / "headerless-api.json").write_text(json.dumps({
    "generated_by": "scripts/publish_headerless.py",
    "library": str(LIB.relative_to(OPB)),
    "filter": FILT.pattern,
    "provenance": "prototypes reconstructed from DWARF (.debug_info) left in the prebuilt archive; "
                  "no vendor source and no code body is included",
    "counts": {"recovered": len(recs), "declared_in_tree_header": len(recs) - len(headless),
               "headerless": len(headless), "headerless_external": len(ext),
               "headerless_static": len(statics), "fully_typed": len(promotable)},
    "functions": sorted(recs, key=lambda r: (r["source"], r["line"] or 0)),
}, indent=1) + "\n")

def sig(r):
    args = ", ".join((a["type"] + " " + a["name"]).strip() if a["name"] else a["type"] for a in r["args"])
    return f"{r['return']} {r['name']}({args or 'void'})"

by_src = collections.defaultdict(list)
for r in ext:
    by_src[r["source"]].append(r)
hdir = ROOT / "include" / "anc_reconstructed"
hdir.mkdir(parents=True, exist_ok=True)
for old in hdir.glob("*.h"):
    old.unlink()
written = []
for src, rs in sorted(by_src.items()):
    stem = pathlib.Path(src).stem
    guard = "ANC_RECONSTRUCTED_" + re.sub(r"\W", "_", stem).upper() + "_H"
    lines = [f"/* {stem}.h - generated by scripts/publish_headerless.py, do not edit.",
             " *",
             f" * Interface of {src} (closed BES implementation), reconstructed from the",
             " * DWARF debug information the vendor left in the prebuilt archive",
             f" * ({len(rs)} functions that no header in this tree declares).",
             " *",
             " * These are declarations only: types refer to definitions elsewhere in this tree,",
             " * the file is not guaranteed to compile standalone, and the implementation behind",
             " * it remains BES's proprietary code - declaration here grants no licence.",
             " */",
             f"#ifndef {guard}", f"#define {guard}", ""]
    for r in sorted(rs, key=lambda r: r["line"] or 0):
        lines.append(f"{sig(r)};  /* line {r['line']} */")
    lines += ["", f"#endif /* {guard} */", ""]
    (hdir / f"{stem}.h").write_text("\n".join(lines))
    written.append((stem + ".h", src, len(rs)))

L = [f"# The closed API that no header declares ({__import__('datetime').date.today().isoformat()})", "",
     f"`{LIB.relative_to(OPB)}`, object names matching `{FILT.pattern}`.", "",
     f"Of {len(recs)} function definitions recovered from DWARF, "
     f"{len(recs) - len(headless)} are declared in a header that ships in the tree and "
     f"**{len(headless)} are not** - the SDK implements them but documents none of them. "
     "Split by linkage:", "",
     f"- **{len(ext)} external** - linkable, so callable from open code and the part of this list that",
     "  constitutes a newly-published API.",
     f"- **{len(statics)} static** - translation-unit private; naming them documents structure but they",
     "  cannot be called even by the blob's own neighbours.",
     "", f"Of the {len(ext)} external ones, **{len(promotable)} have every parameter and the return type "
     "resolved**; the rest reference types that resolve to `?`.", "",
     "Generated by `scripts/publish_headerless.py`. Machine-readable form: "
     "[`data/headerless-api.json`](../data/headerless-api.json). Generated declarations, one file per "
     "vendor source file: [`include/anc_reconstructed/`](../include/anc_reconstructed).", "",
     "Only interface metadata is published - names, types, line numbers. No decompiled code, and no "
     "licence to the implementation, which remains BES's.", "",
     "## Where they come from", "", "| file | external | static |", "|---|---:|---:|"]
for src in sorted(by_src, key=lambda s: -len(by_src[s])):
    st = sum(1 for r in statics if r["source"] == src)
    L.append(f"| `{src}` | {len(by_src[src])} | {st} |")
L += ["", "## The external functions", ""]
for src, rs in sorted(by_src.items()):
    L += [f"### `{src}`", "", "```c"]
    L += [sig(r) + f";  // line {r['line']}" for r in sorted(rs, key=lambda r: r["line"] or 0)]
    L += ["```", ""]
L += ["## The static ones (structure only)", "", "```c"]
L += [sig(r) + f";  // {r['source'].split('/')[-1]}:{r['line']}" for r in sorted(statics, key=lambda r: (r["source"], r["line"] or 0))]
L += ["```", ""]
(ROOT / "docs" / "headerless-api.md").write_text("\n".join(L))
print(f"recovered {len(recs)}: {len(recs)-len(headless)} declared, {len(headless)} header-less "
      f"({len(ext)} external / {len(statics)} static), {len(promotable)} external fully typed")
print("headers:", ", ".join(h for h, _, _ in written))
