#!/usr/bin/env python3
"""Refresh the OpenPineBuds fork survey + fork patch snapshots.

Needs an authenticated `gh` CLI (read access to public repos is enough).
Writes: docs/fork-survey.md, patches/<name>.patch, patches/manifest.json
"""
import json, re, subprocess, sys, pathlib, datetime

UPSTREAM = "pine64/OpenPineBuds"
ROOT = pathlib.Path(__file__).resolve().parent.parent

# forks/branches worth snapshotting as applyable patches (git am)
SOURCES = [
    ("erik-smit", "EriksPineBuds", "main", "configurable touch controls + BLE config service + parametric EQ + Android app"),
    ("nnonickreal", "openqore-sdk", "main", "BES2300P/Soundcore port: working ANC w/ aud section, ADC driver, OTA from source"),
    ("hugohabthroxy", "OpenPineBuds", "main", "BLE advertising on open_source target + cueing service + host tooling"),
    ("RTIS-Lab", "OpenPineBuds", "main", "mic streaming / remote logging over RFCOMM + capture scripts"),
    ("arin-s", "DOOMBuds", "main", "doomgeneric port; SRAM/segment reclaim tricks"),
    ("shymega", "OpenPineBuds", "cmake", "CMake build system conversion (upstream PR #60)"),
    ("shymega", "OpenPineBuds", "rust-support", "CMake + Rust support"),
    ("BreezeLabsAG", "OpenPineBuds", "ph_dsp_bypass", "mic-path DSP bypass modes (normal/breathing/passthrough)"),
    ("BreezeLabsAG", "OpenPineBuds", "SPEECH_TX_EQ_approach", "SPEECH_TX_EQ override experiment"),
    ("BreezeLabsAG", "OpenPineBuds", "SPEECH_TX_MIC_CALIBRATION_approach", "mic calibration experiment"),
    ("SilentBob347", "OpenPineBuds", "anc-tuning", "hand ANC tuning in tgt_hardware.c"),
    ("SilentBob347", "OpenPineBuds", "anc-testing", "audio-section ANC test"),
    ("mbyzhang", "OpenPineBuds", "main", "use ANC FB mic for BT audio (talk-through)"),
    ("jdc-cunningham", "OpenPineBuds", "main", "FR tuning experiments vs measured headphones"),
    ("Zoey-Tan", "OpenPineBuds", "main", "HFP sample-rate experiment + macOS flash scripts"),
]

def filter_binary(patch):
    """Drop binary-file sections (PDFs, images, jars) so patches stay textual and git am-able."""
    idx = patch.find("\ndiff --git ")
    if idx == -1:
        return patch
    head, body = patch[:idx + 1], patch[idx + 1:]
    kept = [sec for sec in re.split(r"(?m)^(?=diff --git )", body)
            if "GIT binary patch" not in sec
            and not re.search(r"(?m)^Binary files .* differ$", sec)]
    return head + "".join(kept)

def gh(args):
    out = subprocess.run(["gh", "api", *args], capture_output=True, text=True, timeout=120)
    if out.returncode:
        raise RuntimeError(out.stderr.strip()[:200])
    return json.loads(out.stdout)

def compare(owner, repo, branch):
    return gh([f"repos/{UPSTREAM}/compare/main...{owner}:{branch}"])

def main():
    forks = json.loads(subprocess.run(
        ["gh", "api", "--paginate", f"repos/{UPSTREAM}/forks?per_page=100"],
        capture_output=True, text=True, encoding="latin-1", timeout=180).stdout)

    rows = []
    for f in forks:
        owner, name = f["owner"]["login"], f["name"]
        try:
            d = compare(owner, name, "main")
        except Exception as e:
            rows.append((owner, name, -1, -1, f["pushed_at"][:10], f"compare failed: {e}"))
            continue
        subs = [c["commit"]["message"].split("\n")[0] for c in d.get("commits", [])]
        rows.append((owner, name, d["ahead_by"], d["behind_by"], f["pushed_at"][:10],
                     "; ".join(subs[-3:])[:150]))
    rows.sort(key=lambda r: (-r[2], r[1].lower()))

    stamp = datetime.date.today().isoformat()
    up = gh([f"repos/{UPSTREAM}"])
    licence = up["license"]["spdx_id"] if up.get("license") else "none"
    lines = [f"# OpenPineBuds forks - survey {stamp}",
             "",
             f"Upstream [`{UPSTREAM}`](https://github.com/{UPSTREAM}) last push `{up['pushed_at'][:10]}`, "
             f"{up['stargazers_count']} stars, {up['forks_count']} forks, {up['open_issues_count']} open issues, "
             f"licence: {licence}.",
             "",
             "`ahead`/`behind` are commit counts versus upstream `main` (default branch of each fork only).",
             "",
             "| fork | ahead | behind | last push | most recent work |",
             "|---|---:|---:|---|---|"]
    for owner, name, ahead, behind, pushed, subs in rows:
        a = "?" if ahead < 0 else ahead
        b = "?" if behind < 0 else behind
        lines.append(f"| [{owner}/{name}](https://github.com/{owner}/{name}) | {a} | {b} | {pushed} | {subs} |")
    zero = sum(1 for r in rows if r[2] == 0)
    lines += ["", f"**{zero} of {len(rows)} forks contain no unique commits.**",
              "", "Generated by `scripts/refresh.py`.", ""]
    (ROOT / "docs" / "fork-survey.md").write_text("\n".join(lines))

    manifest, seen_heads = [], {}
    for owner, repo, branch, why in SOURCES:
        d = compare(owner, repo, branch)
        base = d["merge_base_commit"]["sha"]
        head = d["commits"][-1]["sha"] if d.get("commits") else None
        key = (base, head)
        fname = f"{owner}-{repo}-{branch}.patch"
        if key in seen_heads:
            manifest.append({"fork": f"{owner}/{repo}", "branch": branch, "file": None,
                             "duplicate_of": seen_heads[key], "why": why, "ahead": d["ahead_by"],
                             "behind": d["behind_by"], "base": base, "head": head})
            continue
        seen_heads[key] = fname
        out = subprocess.run(["gh", "api", "-H", "Accept: application/vnd.github.patch",
                              f"repos/{UPSTREAM}/compare/main...{owner}:{branch}"],
                             capture_output=True, text=True, encoding="latin-1", timeout=180)
        if out.returncode or not out.stdout.strip():
            print(f"WARN: no patch for {owner}/{repo}:{branch}", file=sys.stderr)
            continue
        (ROOT / "patches" / fname).write_text(filter_binary(out.stdout), encoding="latin-1")
        manifest.append({"fork": f"{owner}/{repo}", "branch": branch,
                         "file": f"patches/{fname}", "why": why, "ahead": d["ahead_by"],
                         "behind": d["behind_by"], "base": base, "head": head,
                         "files_changed": len(d.get("files", []))})
    (ROOT / "patches" / "manifest.json").write_text(json.dumps(
        {"generated": stamp, "upstream_last_push": up["pushed_at"], "sources": manifest},
        indent=2) + "\n")
    print(f"forks: {len(rows)} ({zero} with no unique commits) | patches written: "
          f"{sum(1 for m in manifest if m.get('file'))} | duplicates skipped: "
          f"{sum(1 for m in manifest if m.get('duplicate_of'))}")

if __name__ == "__main__":
    main()
