#!/usr/bin/env python3
"""Replay every patch in patches/ onto its recorded base commit with `git am --3way`
and report which ones replay cleanly. Needs a clone of upstream OpenPineBuds.

Usage: scripts/verify_patches.py [path-to-upstream-clone]   (default: /tmp/opb)
Writes docs/patch-status.md
"""
import json, os, subprocess, sys, pathlib

ROOT = pathlib.Path(__file__).resolve().parent.parent
CLONE = sys.argv[1] if len(sys.argv) > 1 else os.environ.get("OPB_CLONE", "/tmp/opb")
WT = "/tmp/opb-verify-worktree"

def git(*args, cwd=CLONE, check=False):
    r = subprocess.run(["git", *args], cwd=cwd, capture_output=True, text=True)
    if check and r.returncode:
        raise SystemExit(f"git {' '.join(args)} failed: {r.stderr[:200]}")
    return r

def main():
    if not (pathlib.Path(CLONE) / ".git").exists():
        raise SystemExit(f"no git clone at {CLONE}; clone pine64/OpenPineBuds first "
                         "or pass its path as argv[1]")
    manifest = json.loads((ROOT / "patches" / "manifest.json").read_text())
    rows = []
    for s in manifest["sources"]:
        base, patch = s["base"], ROOT / s["file"]
        git("worktree", "remove", "--force", WT)
        add = git("worktree", "add", "-q", "--detach", WT, base)
        if add.returncode:
            rows.append((s["fork"], s["branch"], "no-base", 0, s["ahead"], "base commit not in clone"))
            continue
        am = git("-c", "user.name=verify", "-c", "user.email=verify@example.invalid",
                 "-C", WT, "am", "--3way", str(patch))
        n = int(git("-C", WT, "rev-list", "--count", f"{base}..HEAD").stdout.strip() or 0)
        blob = am.stdout + am.stderr
        failed_at = ""
        for line in blob.splitlines():
            if line.startswith("Patch failed at "):
                failed_at = line.replace("Patch failed at ", "").strip()
        git("-C", WT, "am", "--abort")
        rows.append((s["fork"], s["branch"], "replays" if am.returncode == 0 else "conflicts",
                     n, s["ahead"], failed_at))
    git("worktree", "remove", "--force", WT)

    ok = sum(1 for r in rows if r[2] == "replays")
    lines = [f"# Patch replay status", "",
             f"Each `patches/*.patch` replayed onto its recorded base commit with `git am --3way`; "
             f"`commits` = commits created / {len(rows)} entries.", "",
             "| fork | branch | result | commits | first conflicting commit |",
             "|---|---|---|---:|---|"]
    for fork, branch, res, n, ahead, failed in rows:
        lines.append(f"| {fork} | {branch} | {res} | {n}/{ahead} | {failed} |")
    lines += ["", f"**{ok}/{len(rows)} patches replay commit-for-commit.**", "",
              "A patch that reports `conflicts` replays part-way: those branches carry commits from "
              "another lineage (e.g. a devcontainer/CMake side-branch) or large parallel merges, so "
              "replay onto the merge-base collides. Use the branch upstream, or resolve the reported "
              "commit by hand.", "",
              "Generated by `scripts/verify_patches.py`.", ""]
    (ROOT / "docs" / "patch-status.md").write_text("\n".join(lines))
    print(f"{ok}/{len(rows)} patches replay cleanly")
    for fork, branch, res, n, ahead, failed in rows:
        if res != "replays":
            print(f"  {res:9} {fork}:{branch} ({n}/{ahead}) {failed[:70]}")

if __name__ == "__main__":
    main()
